version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'java-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 3.1.5fortest


  app:
    build: ./
    container_name: 'java_app'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/3.1.5fortest
    depends_on:
      - mysql